#!/usr/bin/env bash
echo "== A bucket is created"

# Checks if an argument is an empty string or not
if [[ -z "$1" ]] ;
  then
    echo "No bucket name provided eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME 
--create-bucket-configuration="LocationConstraint=us-east-1"
--query Location
--output text