#!/usr/bin/env bash
echo "== Your bucket is deleted"

# Checks if an aegument is an empty string or not
if [[ -z "$1" ]] ;
  then
    echo "No bucket name provided eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket --bucket $BUCKET_NAME 
